import type { Metadata } from 'next'
import { Hero } from '@/components/Hero'
import { Section, Eyebrow, Heading } from '@/components/Section'
import { Card, Timeline } from '@/components/Cards'
import { Button } from '@/components/Button'
export const metadata: Metadata = { title: 'The Boudoir Experience', description: 'A private, guided boudoir experience designed around comfort, styling, posing, privacy, and confidence.' }
const items = [
 { title:'Inquiry', body:'You reach out through our contact form or email. We respond within 24 hours ready to answer any questions about your experience.'},
 { title:'Consultation Call', body:'We schedule a private phone call to discuss your vision, any nervousness, comfort level, wardrobe preferences, and what this experience means to you.'},
 { title:'Styling Guidance', body:'You receive personalized recommendations for lingerie, robes, oversized shirts, dresses, jewelry, and pieces that feel natural and empowering.'},
 { title:'Location & Logistics', body:'Choose from studio, hotel, Airbnb, in-home, or destination options across Destin and 30A. We confirm your date, time, and any final details.'},
 { title:'Pre-Shoot Prep', body:'A few days before your session, we send a questionnaire about your comfort level and what to expect. You arrive prepared and confident.'},
 { title:'The Session', body:'Spend 1 to 3 hours creating beautiful, artistic images — time varies based on your session type, whether hair and makeup are included, and your outfit selections. Every pose, expression, hand placement, and movement is guided. You never have to perform.'},
 { title:'Private Reveal', body:'You view your images in a private session. We walk through your favorites and discuss which images resonate most with you.'},
 { title:'Sales & Selection', body:'You choose your albums, artwork, or digital collections. Take home your investment and enjoy them for a lifetime.'},
]
export default function Page(){return <main><Hero eyebrow="The Experience" title="A Boudoir Experience Designed Around Your Comfort" subtitle="From the moment you inquire, you are guided through every step — styling, posing, privacy, expression, and final image selection."/><Section><div className="grid gap-8 md:grid-cols-3"><Card title="You never have to wonder">We guide what to do with your hands, eyes, posture, expression, and movement.</Card><Card title="You never have to force confidence">Confidence is created through comfort, direction, lighting, and trust.</Card><Card title="You never have to over-reveal">Your session can be soft, covered, implied, bold, romantic, playful, or anywhere in between.</Card></div></Section><Section><div className="max-w-2xl"><Eyebrow>Before the session</Eyebrow><Heading>You start with a private consultation.</Heading><div className="prose-luxury text-lg mt-6 space-y-4"><p>Boudoir requires trust, which is why every client speaks with me privately before booking. This is where I stop being a brand and show up as a real person.</p><p>We'll talk about what excites you and what makes you nervous. I'll ask about your vision, comfort level, wardrobe style, privacy concerns, and any questions about the process. You'll get to know my energy, ask anything, and decide if this feels right for you.</p><p><strong>This consultation is free, private, and pressure-free.</strong> There's no obligation to book. This is simply a conversation about whether the experience feels right for you.</p></div></div></Section><Section className="bg-smoke"><Eyebrow>Your session flow</Eyebrow><Heading>Everything is intentional, private, and paced around you.</Heading><div className="mt-12"><Timeline items={items}/></div></Section><Section><div className="max-w-2xl"><Eyebrow>Why this process</Eyebrow><Heading>Clear expectations create the best experience.</Heading><div className="prose-luxury text-lg mt-6 space-y-4"><p>Each step in your journey is intentional. We don't rush through booking, styling, or consultation. Why? Because the more you understand what to expect, the more comfortable you feel. And the more comfortable you feel, the more empowered you become.</p><p>This isn't just about beautiful photos. It's about a complete experience where you feel heard, guided, and celebrated from your first email to the moment you hold your finished album.</p></div></div></Section><Section><div className="grid gap-8 md:grid-cols-2"><Card title="Privacy & Consent">Your images are never shared without written permission. Your comfort level is discussed before the session and respected throughout.</Card><Card title="Payment Planning">Payment plans are available so you can plan your experience and artwork without pressure.</Card></div><div className="mt-10"><Button href="/contact">Plan My Session</Button></div></Section></main>}
