export const site = {
  name: 'Second Skin Boudoir',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://secondskinboudoir.com',
  phone: '850-608-0844',
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'hello@secondskinboudoir.com',
  location: 'Destin, Florida',
  areas: ['Destin', '30A', 'Santa Rosa Beach', 'Miramar Beach', 'Fort Walton Beach', 'Panama City Beach', 'Florida Gulf Coast'],
}

export const nav = [
  { label: 'Experience', href: '/experience' },
  { label: 'Portfolio', href: '/boudoir-portfolio' },
  { label: 'Opportunities', href: '/opportunities' },
  { label: 'Pricing', href: '/boudoir-pricing' },
  { label: 'FAQ', href: '/faq' },
  { label: 'About', href: '/about' },
]

export const galleryImages = [
  { image: '/images/boudoir/LW-263.jpg', alt: 'Luxury intimate boudoir photography' },
  { image: '/images/boudoir/LW2-01.jpg', alt: 'Contemporary boudoir photography' },
  { image: '/images/boudoir/LW-260.jpg', alt: 'Timeless boudoir photography portrait' },
  { image: '/images/boudoir/EG-01.jpg', alt: 'Elegant intimate boudoir portrait' },
  { image: '/images/boudoir/LW-256.jpg', alt: 'Beautiful boudoir photography' },
  { image: '/images/boudoir/KK-03.jpg', alt: 'Confident boudoir photography' },
  { image: '/images/boudoir/LW2-11.jpg', alt: 'Artistic boudoir photography portrait' },
  { image: '/images/boudoir/LW-242.jpg', alt: 'Artistic boudoir photography' },
  { image: '/images/boudoir/EG-17.jpg', alt: 'Artistic boudoir photography detail' },
  { image: '/images/boudoir/LW-228.jpg', alt: 'Elegant intimate boudoir' },
  { image: '/images/boudoir/LW-207.jpg', alt: 'Contemporary boudoir photography' },
  { image: '/images/boudoir/LW2-15.jpg', alt: 'Sensual boudoir composition' },
  { image: '/images/boudoir/LW-206.jpg', alt: 'Serene boudoir portrait' },
  { image: '/images/boudoir/KK-06.jpg', alt: 'Empowered boudoir portrait' },
  { image: '/images/boudoir/EG-38.jpg', alt: 'Romantic boudoir photography' },
  { image: '/images/boudoir/LW-184.jpg', alt: 'Sensual boudoir photography' },
  { image: '/images/boudoir/LW-176.jpg', alt: 'Artistic boudoir composition' },
  { image: '/images/boudoir/LW2-24.jpg', alt: 'Luxurious boudoir portrait' },
  { image: '/images/boudoir/EG-41.jpg', alt: 'Beautiful boudoir fashion photography' },
  { image: '/images/boudoir/LW-161.jpg', alt: 'Artistic boudoir photography silhouette' },
  { image: '/images/boudoir/LW-160.jpg', alt: 'Romantic intimate boudoir' },
  { image: '/images/boudoir/LW-156.jpg', alt: 'Romantic boudoir photography' },
  { image: '/images/boudoir/KK-09.jpg', alt: 'Artistic intimate boudoir' },
  { image: '/images/boudoir/EG-46.jpg', alt: 'Empowering boudoir photography' },
  { image: '/images/boudoir/LW-153.jpg', alt: 'Tasteful boudoir photography detail' },
  { image: '/images/boudoir/LW-147.jpg', alt: 'Empowering boudoir photography' },
  { image: '/images/boudoir/LW-146.jpg', alt: 'Intimate boudoir portrait' },
  { image: '/images/boudoir/EG-47.jpg', alt: 'High-fashion editorial boudoir photography' },
  { image: '/images/boudoir/LW2-29.jpg', alt: 'Tasteful boudoir composition' },
  { image: '/images/boudoir/LW-142.jpg', alt: 'High-fashion editorial boudoir photography' },
  { image: '/images/boudoir/EG-53.jpg', alt: 'Boudoir photography artistic portrait' },
  { image: '/images/boudoir/KK-10.jpg', alt: 'Stunning boudoir composition' },
  { image: '/images/boudoir/LW2-33.jpg', alt: 'Intimate boudoir photography' },
  { image: '/images/boudoir/LW-104.jpg', alt: 'Boudoir photography artistic portrait' },
  { image: '/images/boudoir/LW-093.jpg', alt: 'Beautiful boudoir fashion photography' },
  { image: '/images/boudoir/LW-089.jpg', alt: 'Elegant intimate photography' },
  { image: '/images/boudoir/EG-65.jpg', alt: 'Luxury boudoir photography' },
  { image: '/images/boudoir/LW-060.jpg', alt: 'Elegant boudoir photography portrait' },
  { image: '/images/boudoir/LW2-47.jpg', alt: 'Beautiful boudoir composition' },
  { image: '/images/boudoir/LW-055.jpg', alt: 'Empowerment boudoir photography' },
  { image: '/images/boudoir/LW-052.jpg', alt: 'Tasteful boudoir composition' },
  { image: '/images/boudoir/KK-19.jpg', alt: 'Luxurious boudoir portrait' },
  { image: '/images/boudoir/LW-047.jpg', alt: 'Artistic boudoir photography detail' },
  { image: '/images/boudoir/EG-75.jpg', alt: 'Intimate boudoir portrait' },
  { image: '/images/boudoir/LW2-49.jpg', alt: 'Empowered boudoir portrait' },
  { image: '/images/boudoir/LW-030.jpg', alt: 'Serene boudoir photography' },
  { image: '/images/boudoir/LW-024.jpg', alt: 'Artistic intimate portrait' },
  { image: '/images/boudoir/LW-008.jpg', alt: 'Boudoir photography showing confidence and elegance' },
  { image: '/images/boudoir/LW-006.jpg', alt: 'Luxury boudoir photography portrait' },
  { image: '/images/boudoir/LM1.jpg', alt: 'Luxury boudoir photography portrait' },
  { image: '/images/boudoir/LM2.jpg', alt: 'Intimate boudoir portrait' },
  { image: '/images/boudoir/LM3.jpg', alt: 'Artistic boudoir photography' },
  { image: '/images/boudoir/LM4.jpg', alt: 'Elegant boudoir photography' },
  { image: '/images/boudoir/LM6.jpg', alt: 'Beautiful boudoir composition' },
]

export const faqs = [
  ['Is boudoir photography empowering?', 'Absolutely. Boudoir photography is designed to help you reconnect with your beauty, confidence, and sense of self. It\'s a celebration of who you are right now — not who you think you should be. Many of our clients describe their boudoir session as transformative, leaving with a new appreciation for their body and a boost in confidence that lasts long after the session ends.'],
  ['Is boudoir for me?', 'Yes. Boudoir is for any woman who wants to feel more connected to her beauty, confidence, sensuality, or body. You do not need to be a certain size, age, relationship status, or confidence level. We work with women of all ages, body types, and backgrounds. Whether you\'re in your 20s or 60s, athletic or curvy, this experience is for you.'],
  ['What should I wear?', 'Whatever feels like your second skin. Lingerie, an oversized shirt, a favorite dress, or nothing at all — we will help you choose pieces that make you feel powerful, comfortable, and gorgeous. Once you book your session, you\'ll receive a detailed What to Wear guide with styling tips and inspiration photos tailored to your session type. You can also <a href="/what-to-wear-boudoir-session" style="color: #d9bf7c; text-decoration: underline; font-weight: 500;">browse our complete wardrobe guide</a> to explore 25+ outfit ideas and styling recommendations now.'],
  ['Will it be awkward?', 'Only for the first five minutes. We guide your posing, talk you through every step, and keep the vibe fun and relaxed until being in front of the camera feels like second nature. Most clients find themselves laughing and having a genuine good time within the first 15 minutes. By the end, you\'ll feel like you\'ve spent an afternoon with a trusted friend who happens to be amazing at making you look stunning.'],
  ['How long does it take?', 'Most sessions run 2-3 hours, depending on your package and outfit changes. This includes time for hair and makeup, wardrobe changes, posing, and a reveal moment where we show you some of your favorites. We take our time so you never feel rushed — just fully in the moment, enjoying the experience.'],
  ['What if I\'m nervous about how I look?', 'That is totally normal. That is why Second Skin Boudoir exists — to help you see what is already there. We pose you, light you, and cheer you on so when you see the final images, you recognize the person you have always been. Many clients with body concerns find that the images reveal a beauty they never noticed in the mirror.'],
  ['Who will be doing my photo shoot?', 'Matthew, a professional, calm, guided, and privacy-first boudoir photographer dedicated to creating safe, empowering experiences. Before your shoot, you will have a private consultation to discuss your vision, comfort level, and any concerns. During the session, every pose, expression, hand placement, and movement is directed step by step. Visit the About page to learn more about Matthew\'s approach and philosophy. You may also bring a trusted friend as long as they will be supportive and positive.'],
  ['Where do sessions take place?', 'We have favorite studio, hotel, and Airbnb spots throughout the Florida Gulf Coast, including Destin, 30A, Santa Rosa Beach, Miramar Beach, Fort Walton Beach, and Panama City Beach. We can also arrange in-home or in-hotel sessions if you prefer. No matter where you are located, we\'ll work with you to find the perfect location for your session.'],
  ['Can I afford to do this?', 'We believe that all women should have the opportunity to feel good in their body and strive to make our services accessible to as many women as possible. We offer different levels of packages and also offer pre and post payment plans to pay over time. Session fees begin at $300, with products starting at $995 and interest-free payment plans available.'],
  ['What if I don\'t like the pictures or have a bad experience?', 'This doesn\'t happen, and it never has! You will actually have a harder time finding images you don\'t like. However, we are so confident in our work and the experience you will get, that if you don\'t like your images or do not have an amazing experience, we will happily give you a refund.'],
  ['I\'m not a size 2, is boudoir for me?', 'More than yes. Most of our clients are moms, over the age of 30, and definitely NOT a size 2 — or even a 10. Posing and lighting for every body is our specialty. We work with curves, straight figures, athletic builds, and everything in between. We\'ve also photographed clients with stretch marks, scars, and tattoos — and every session celebrates exactly what makes you unique. You are beautiful exactly as you are, right now.'],
  ['Do you share all of my images on the internet?', 'Absolutely not! I only share images that my clients sign a release for allowing me to share. There are different levels of sharing too. You can choose to share only anonymous images, share publicly, or keep your images completely private.'],
  ['Do I need to know how to pose?', 'No. All of our clients are real women, just like you. We take care of the posing right down to your fingertips. By the end of your session, you might just feel like a supermodel!'],
  ['Do you photograph men or couples boudoir?', 'Not at this time. We specialize exclusively in women-centered boudoir experiences.'],
  ['I never wear lingerie or don\'t think it looks good on me. What do I do?', 'Many of our clients feel this way. Our suggestion is to go into a lingerie store to get support from knowledgeable staff and try on a variety of pieces. Once you figure out what you like and what fits best, you can try online shopping. And remember, you don\'t have to wear lingerie for every set! Bring in a pair of your favorite jeans, an oversized sweater, a white tank, body jewelry, etc.'],
  ['Who will be at my session?', 'Your boudoir session is a private, closed event, meaning that only the makeup artist will be there (if your session includes hair and makeup) to get you ready, and then your photographer for the entirety of your session.'],
  ['Will you Photoshop me?', 'We happily offer retouching on all our photos, which includes overall skin smoothing, evening out uneven skin tone, and removing stray hairs. We also fix minor wardrobe malfunctions, which means we even out areas where the lingerie might be cutting into the skin. However, we do not provide body sculpting or extensive forms of retouching. Our motto: if it is a permanent part of your body, it stays; if it is a temporary imperfection, it goes.'],
  ['What is the average cost of a boudoir shoot?', 'Our studio uses a Session Fee + Products model. Your session is one flat fee ($300 or $549) and includes your entire experience, professional hair and makeup, wardrobe styling, your session, and your reveal session. Products are purchased separately, starting at $995, so you are never locked into a package before you even know what you will love. You only buy the images that make you say "that\'s me!"'],
  ['Do you offer payment plans?', 'Absolutely. We offer interest-free payment plans both before and after your session. Our Pre-Session Payment Plans let you save toward your products before your shoot — you choose the monthly amount and everything becomes credit toward your final order. We also offer Post-Session Payment Plans after you see your images, so you can select your favorite photos and spread the investment across multiple payments.'],
  ['How long does it take to get my album?', 'It usually takes about 3-4 weeks. Some products take a bit longer. You will have full visibility into your timeline.'],
  ['I\'m concerned about a male photographer. How do you ensure my comfort and safety?', 'Your safety and comfort come first. Matthew is a calm, respectful, professional who specializes in making clients feel empowered and protected. Every session starts with a private consultation where you discuss your boundaries, comfort level, and any concerns. During your session, you have complete control — you can pause, modify, or stop anything at any time. You\'re never pressured, and you can bring a trusted friend if that helps you feel more comfortable. This approach has earned Matthew deep trust with hundreds of clients who initially had similar concerns.'],
  ['What makes Matthew\'s approach different from other photographers?', 'Matthew built Second Skin Boudoir on three core principles: Privacy first (images are never shared without permission), Respect always (communication and consent guide every moment), and Direction throughout (you\'re guided through every pose so you never have to guess or perform). He specializes in helping first-time clients feel safe, beautiful, and powerful. The experience is intentional, calm, and designed around what you need — not what looks good on film.'],
  ['Is boudoir only for married women or women in relationships?', 'Not at all! Boudoir photography is for any woman who wants to celebrate herself — single, married, divorced, widowed, or anything in between. Many single women book boudoir sessions to celebrate their independence, boost their confidence, or simply because they deserve to feel beautiful. Whether it\'s a gift for yourself, your partner, or both, this is your moment.'],
  ['What should I do to prepare for my boudoir session?', 'We\'ll send you detailed preparation instructions after booking, but here are the basics: Get a good night\'s sleep the night before, stay hydrated, avoid major sun exposure (we want your skin looking fresh), and wear comfortable clothing to the session. We recommend scheduling the day before your period if possible, as some clients feel more bloated during their cycle. Most importantly, come with an open mind and a willingness to have fun!'],
  ['What\'s included in my boudoir session?', 'Your session fee includes professional hair and makeup, wardrobe styling consultation, your full photography session, direction throughout all poses, and a private reveal appointment to see and select your favorite images. You\'ll also receive a detailed What to Wear guide before your session, access to our 25+ styling inspiration ideas, and a private consultation to discuss your vision and comfort level.'],
  ['Can I bring props or request specific outfit/pose ideas?', 'Absolutely! We encourage personalization. Whether you have a specific outfit you want to wear, props that mean something to you, or pose ideas you\'ve seen, we\'re happy to work with you. This is your session, and we want it to reflect who you are. Just let us know during your consultation so we can plan accordingly.'],
  ['What if I have tattoos, scars, or stretch marks?', 'We celebrate them! Tattoos, scars, and stretch marks are part of your story, and they\'re beautiful. Our posing and lighting techniques work beautifully with every body, including those with visible marks or changes. If you\'re self-conscious about something specific, let us know during your consultation and we\'ll address it with sensitivity and skill.'],
  ['When is the best time to book a boudoir session?', 'Boudoir sessions are perfect for any occasion: celebrating yourself, a birthday, an anniversary, a major life milestone, after a breakup or new chapter, or simply because you deserve it. Many clients book several months in advance for special occasions. There\'s no "right" time — just when you feel ready to invest in yourself and celebrate your beauty.'],
  ['What\'s the difference between boudoir and glamour photography?', 'Boudoir photography focuses on intimacy, sensuality, and self-love in a private, empowering context. It\'s about celebrating your body and femininity in tasteful, artistic ways. Glamour photography tends to be more about polished, styled photos for general purposes. Boudoir is personal, intimate, and deeply empowering — it\'s a transformative experience, not just beautiful photos.'],
  ['How do I decide which images and products to order?', 'After your session, you\'ll come back for a private reveal appointment. We\'ll show you the best selections in a beautiful presentation, and you can take your time deciding which images speak to you. Since there\'s no package lock-in, you only order what you truly love. We\'ll help guide you, but the choice is 100% yours. Many clients find they love far more images than they expected!'],
]
